---
title: "Core Demographics"
author: "Elizabeth McNeilly"
date: "12/8/2019"
output: html_document
---

#NOTE: 
- This script was originally written for the 2019 ABCD Workshop (data release 2.0) and has been edited for the recent 3.0 release. 
#SETUP
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)

#Set your directory with merged data set (nda20) here:

# Elizabeth.
# Data: Desktop⁩ ▸ ⁨ABCD⁩ ▸ ⁨derivatives⁩ ▸ ⁨exploratory⁩
# Code: Desktop⁩ ▸ ⁨rewardprocesses_internalizing_puberty_exploratory⁩ ▸ ⁨code⁩

# Lucia.
# Data:  Github⁩ ▸ ⁨ABCD⁩ ▸ ⁨derivatives⁩ ▸ ⁨exploratory⁩
# Code:  Github ▸ ⁨rewardprocesses_internalizing_puberty_exploratory⁩ ▸ ⁨code

# Natalie.
# Data:  Desktop ▸ ABCD⁩ ▸ ⁨ABCD⁩ ▸ ⁨derivatives⁩ ▸ ⁨exploratory⁩
# Code:  Desktop ▸ ABCD ⁩▸ ⁨rewardprocesses_internalizing_puberty_exploratory⁩ ▸ ⁨code

# LMW alternative to read in the data.

data_dir = ((dirname(here()))) 
data_folder <- file.path(data_dir,"ABCD","derivatives")
output_directory <- data_folder

#file_name <- "nda20.csv" # specify file name here. 

#fulldata <- read.csv(file.path(data_folder,file_name))
#output_directory <- "~/Desktop/Desktop_MacBookPro/Desktop_Folders/UO/ABCD_Workshop/Data_Analysis_3.0/Output"   #EM

#output_directory <- "C:\\Users\\lucia\\GitHub\\ABCD\\derivatives"   #LMW
#output_directory <- "/Users/nataliesaragosa-harris/Desktop/ABCD/output"

```

```{r}
## Definition of convenience variables

# The following sections extend the nda20 data frame (see [creating a single data spreadsheet](https://github.com/ABCD-STUDY/analysis-nda17#create-a-single-data-spreadsheet) and [create categorical variables](https://github.com/ABCD-STUDY/analysis-nda/blob/master/notebooks/general/categorical_extension.md)) by some core demographic columns.
#  - subjectid
#  - age in years
#  - sex
#  - female
#  - race.ethnicity
#  - household.income
#  - high.educ
#  - married
#  - abcd_site

# Most of these are simple re-definitions of existing columns with simpler names, other columns are re-scored versions of nda17 columns.
```


```{r}
# Start by reading in the merged data from disk.

#nda20 = readRDS(paste(output_directory,"nda20.rds",sep="/"))
nda20 = readRDS(paste(output_directory,"nda20.rds",sep="/"))

# Now extend nda20 by the new columns.

### Site name
# The site name is anonymized and stored per event in case participants move from one site to another during the study.

nda20$abcd_site = nda20$site_id_l

### Subjectid

nda20$subjectid = nda20$src_subject_id

### Age (in month)
# Get a better name for interview_age.

nda20$age = nda20$interview_age

### Household income

#1= Less than $5,000; 2=$5,000 through $11,999; 3=$12,000 through $15,999; 4=$16,000 through $24,999; 5=$25,000 through $34,999; 6=$35,000 through $49,999; 7=$50,000 through $74,999; 8= $75,000 through $99,999; 9=$100,000 through $199,999; 10=$200,000 and greater. 999 = Don't know; 777 = Refuse to answer.

household.income = nda20$demo_comb_income_v2
household.income[nda20$demo_comb_income_v2 == "777"] = NA
household.income[nda20$demo_comb_income_v2 == "999"] = NA
household.income[nda20$demo_comb_income_v2 == "1"] = 1 # "[<5K]"
household.income[nda20$demo_comb_income_v2 == "2"] = 2 # "[5K-12K]"
household.income[nda20$demo_comb_income_v2 == "3"] = 3 # "[12K-16K]"
household.income[nda20$demo_comb_income_v2 == "4"] = 4 # "[16K-25K]"
household.income[nda20$demo_comb_income_v2 == "5"] = 5 # "[25K-35K]"
household.income[nda20$demo_comb_income_v2 == "6"] = 6 # "[35K-50K]"
household.income[nda20$demo_comb_income_v2 == "7"] = 7 # "[50K-75K]"
household.income[nda20$demo_comb_income_v2 == "8"] = 8 # "[75K-100K]"
household.income[nda20$demo_comb_income_v2 == "9"] = 9 # "[100K-200K]"
household.income[nda20$demo_comb_income_v2 == "10"] = 10 # "[>=200K]"
nda20$household.income = factor(household.income, levels= 1:10, labels = c("[<5K]",
                                                                               "[5K-12K]",
                                                                               "[12K-16K]",
                                                                               "[16K-25K]",
                                                                               "[25K-35K]",
                                                                               "[35K-50K]",
                                                                               "[50K-75K]",
                                                                               "[75K-100K]",
                                                                               "[100K-200K]",
                                                                               "[>=200K]"))
                                      
#temp <- nda20[,c("eventname","demo_comb_income_v2", "household.income")]
#temp <- subset(temp,eventname=="baseline_year_1_arm_1")

### Highest level of parental education
# This can be either the first (demo_prnt_ed_v2) or the second (demo_prtnr_ed_v2) parent.

highest.education = rep("999", length(nda20$demo_prnt_ed_v2))
highest.education[nda20$demo_prnt_ed_v2 == "0"] = 1
highest.education[nda20$demo_prnt_ed_v2 == "1"] = 4
highest.education[nda20$demo_prnt_ed_v2 == "2"] = 5
highest.education[nda20$demo_prnt_ed_v2 == "3"] = 6
highest.education[nda20$demo_prnt_ed_v2 == "4"] = 7
highest.education[nda20$demo_prnt_ed_v2 == "5"] = 8
highest.education[nda20$demo_prnt_ed_v2 == "6"] = 9
highest.education[nda20$demo_prnt_ed_v2 == "7"] = 10
highest.education[nda20$demo_prnt_ed_v2 == "8"] = 11
highest.education[nda20$demo_prnt_ed_v2 == "9"] = 12
highest.education[nda20$demo_prnt_ed_v2 == "10"] = 13
highest.education[nda20$demo_prnt_ed_v2 == "11"] = 14
highest.education[(nda20$demo_prnt_ed_v2 == "12") | (nda20$demo_prnt_ed_v2 == "13")] = 16
highest.education[nda20$demo_prnt_ed_v2 == "14"] = 17
highest.education[nda20$demo_prnt_ed_v2 == "15"] = 18
highest.education[(nda20$demo_prnt_ed_v2 == "16") | (nda20$demo_prnt_ed_v2 == "17")] = 20
highest.education[nda20$demo_prnt_ed_v2 == "18"] = 21
highest.education[nda20$demo_prnt_ed_v2 == "19"] = 22
highest.education[nda20$demo_prnt_ed_v2 == "20"] = 23
highest.education[nda20$demo_prnt_ed_v2 == "21"] = 24
highest.education[nda20$demo_prnt_ed_v2 == "777"] = 999
highest.education[highest.education == 999] = NA

highest.education2 = rep("999", length(nda20$demo_prtnr_ed_v2))
highest.education2[nda20$demo_prtnr_ed_v2 == "0"] = 1
highest.education2[nda20$demo_prtnr_ed_v2 == "1"] = 4
highest.education2[nda20$demo_prtnr_ed_v2 == "2"] = 5
highest.education2[nda20$demo_prtnr_ed_v2 == "3"] = 6
highest.education2[nda20$demo_prtnr_ed_v2 == "4"] = 7
highest.education2[nda20$demo_prtnr_ed_v2 == "5"] = 8
highest.education2[nda20$demo_prtnr_ed_v2 == "6"] = 9
highest.education2[nda20$demo_prtnr_ed_v2 == "7"] = 10
highest.education2[nda20$demo_prtnr_ed_v2 == "8"] = 11
highest.education2[nda20$demo_prtnr_ed_v2 == "9"] = 12
highest.education2[nda20$demo_prtnr_ed_v2 == "10"] = 13
highest.education2[nda20$demo_prtnr_ed_v2 == "11"] = 14
highest.education2[(nda20$demo_prtnr_ed_v2 == "12") | (nda20$demo_prtnr_ed_v2 == "13")] = 16
highest.education2[nda20$demo_prtnr_ed_v2 == "14"] = 17
highest.education2[nda20$demo_prtnr_ed_v2 == "15"] = 18
highest.education2[(nda20$demo_prtnr_ed_v2 == "16") | (nda20$demo_prtnr_ed_v2b == "17")] = 20
highest.education2[nda20$demo_prtnr_ed_v2 == "18"] = 21
highest.education2[nda20$demo_prtnr_ed_v2 == "19"] = 22
highest.education2[nda20$demo_prtnr_ed_v2 == "20"] = 23
highest.education2[nda20$demo_prtnr_ed_v2 == "21"] = 24
highest.education2[nda20$demo_prtnr_ed_v2 == "777"] = 999
highest.education2[highest.education2 == 999] = NA
nda20$highest.education = factor( as.character(pmax(as.numeric(highest.education), as.numeric(highest.education2),na.rm=T)), levels=c(9,10,11,12,13,14,15,16,17,18,20,21,22,23,24), labels=c("9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "20", "21", "22", "23", "24") )


# Here a simplified version of the highest education that results in only 5 different levels. These levels correspond to the numbers published by the American Community Survey (ACS).

high.educ1 = nda20$demo_prnt_ed_v2
high.educ2 = nda20$demo_prtnr_ed_v2
high.educ1[which(high.educ1 == "999")] = NA
high.educ2[which(high.educ2 == "999")] = NA
high.educ1[which(high.educ1 == "777")] = NA
high.educ2[which(high.educ2 == "777")] = NA
high.educ = pmax(as.numeric(as.character(high.educ1)), as.numeric(as.character(high.educ2)), na.rm=T)
idx <- which(high.educ %in% 0:12, arr.ind = TRUE)
high.educ[idx] = 1 # "< HS Diploma"
idx <- which(high.educ %in% 13:14, arr.ind = TRUE)
high.educ[idx] = 2 # "HS Diploma/GED"
idx <- which(high.educ %in% 15:17, arr.ind = TRUE)
high.educ[idx] = 3 # "Some College"
idx <- which(high.educ == 18, arr.ind = TRUE)
high.educ[idx] = 4 # "Bachelor"
idx <- which(high.educ %in% 19:21, arr.ind = TRUE)
high.educ[idx] = 5 # "Post Graduate Degree"
high.educ[which(high.educ == "999")]=NA
high.educ[which(high.educ == "777")]=NA
nda20$high.educ = factor( high.educ, levels= 1:5, labels = c("< HS Diploma","HS Diploma/GED","Some College","Bachelor","Post Graduate Degree") )


# temp2 <- nda20[,c("eventname","demo_prnt_ed_v2", "demo_prtnr_ed_v2", "highest.education","high.educ")]
# temp2 <- subset(temp2,eventname=="baseline_year_1_arm_1")

### Marital status.

# The demo_prnt_marital_v2 variable has also been renamed in NDA_DEAP_names_2.0.csv to demo_prnt_marital_v2b.


married = rep(NA, length(nda20$demo_prnt_marital_v2))
married[nda20$demo_prnt_marital_v2 == 1] = 1
married[nda20$demo_prnt_marital_v2 %in% 2:6] = 0
nda20$married = factor( married, levels= 0:1, labels = c("no", "yes") )

# Add another variable that also includes couples that just live together.

married.livingtogether = rep(NA, length(nda20$demo_prnt_marital_v2))
married.livingtogether[nda20$demo_prnt_marital_v2 %in% c(1,6)] = 1
married.livingtogether[nda20$demo_prnt_marital_v2 %in% 2:5] = 0
nda20$married.or.livingtogether = factor(married.livingtogether, levels= 0:1, labels = c("no", "yes") )

# temp3 <- nda20[,c("eventname","demo_prnt_marital_v2","married.or.livingtogether")]
# temp3 <- subset(temp3,eventname=="baseline_year_1_arm_1")

#Keeping BMI calculation in case we want it in the future:

### Body-Mass index 

#nda20$anthro_bmi_calc = as.numeric(as.character(nda20$anthro_weight_calc)) / #as.numeric(as.character(nda20$anthro_height_calc))^2 * 703
#nda20$anthro_bmi_calc[which(nda20$anthro_bmi_calc>100)]=NA
```


```{r}
### A simplified race.ethnicity value

# ABCD is using a simplified 5 category race/ethnicity scale for reporting purposes and for comparison of the ABCD cohort to data from the American Community Census. The following code will add a new 'race_ethnicity' column to the NDA-20 data frame that implement this scale.


nda20$demo_race_white= (nda20$demo_race_a_p___10 == 1)*1
nda20$demo_race_black= (nda20$demo_race_a_p___11 == 1)*1
nda20$demo_race_asian = 0
nda20$demo_race_asian[nda20$demo_race_a_p___18 == 1 | nda20$demo_race_a_p___19 == 1 |
			nda20$demo_race_a_p___20 == 1 | nda20$demo_race_a_p___21 == 1 |
			nda20$demo_race_a_p___22 == 1 | nda20$demo_race_a_p___23 == 1 |
		    nda20$demo_race_a_p___24==1] = 1
nda20$demo_race_aian = 0
nda20$demo_race_aian[nda20$demo_race_a_p___12 == 1 | nda20$demo_race_a_p___13 == 1] = 1
nda20$demo_race_nhpi = 0
nda20$demo_race_nhpi[nda20$demo_race_a_p___14 == 1 | nda20$demo_race_a_p___15 == 1 |
				nda20$demo_race_a_p___16 == 1 | nda20$demo_race_a_p___17 == 1] = 1
nda20$demo_race_other = 0
nda20$demo_race_other[nda20$demo_race_a_p___25 == 1] = 1
nda20$demo_race_mixed = nda20$demo_race_white + nda20$demo_race_black + nda20$demo_race_asian +
					nda20$demo_race_aian + nda20$demo_race_nhpi + nda20$demo_race_other

nda20$demo_race_mixed[ nda20$demo_race_mixed <= 1] =  0
nda20$demo_race_mixed[ nda20$demo_race_mixed > 1] =  1


# Let's keep the race and ethnicity (Hispanic/Latinx) separate.
nda20$race.eth.7level = NA
nda20$race.eth.7level[ nda20$demo_race_white == 1] = 1
nda20$race.eth.7level[ nda20$demo_race_black == 1] = 2
nda20$race.eth.7level[ nda20$demo_race_asian == 1] = 3
nda20$race.eth.7level[ nda20$demo_race_aian == 1]  = 4
nda20$race.eth.7level[ nda20$demo_race_nhpi == 1]  = 5
nda20$race.eth.7level[ nda20$demo_race_other == 1] = 6
nda20$race.eth.7level[ nda20$demo_race_mixed == 1] = 7

# demo_ethn_v2 : do you consider the child Hispanic/Latino/Latina?
# 1 = Yes; 2 = No.
nda20$demo_race_hispanic=NA; 
nda20$demo_race_hispanic[nda20$demo_ethn_v2 == 1] = 1 
nda20$demo_race_hispanic[nda20$demo_ethn_v2 == 2] = 0

nda20$race.eth.7level <- factor(nda20$race.eth.7level,
                       levels = c(1,2,3,4,5,6,7),
                       labels = c("White", "Black", "Asian", "AIAN", "NHPI", "Other", "Mixed") )


# The above race.eth value has more categories compared to what has been used recently in ABCD. Here is the reduced definition of race/ethnicity used most frequently.
nda20$race.ethnicity.5level = nda20$race.eth.7level
nda20$race.ethnicity.5level[(nda20$race.eth.7level == "AIAN" | nda20$race.eth.7level == "NHPI")] = "Other"
nda20$race.ethnicity.5level = droplevels(nda20$race.ethnicity.5level)


#temp4 <- nda20[,c("eventname","demo_race_white","demo_race_black","demo_race_asian","demo_race_aian","demo_race_nhpi","demo_race_other","demo_race_mixed","demo_race_hispanic","race.eth.7level","race.ethnicity.5level")]
# temp4 <- subset(temp4,eventname=="baseline_year_1_arm_1")

# It is worthwhile to point out here that the above category for Hispanic is calculated in ABCD differently from the other race categories. In particular any ethnicity selection of hispanic will map the participant into the hispanic category regardless of the selection of one or more race categories.

# summary(temp4$race.ethnicity.5level)
# White Black Asian Other Mixed  NA's 
# 7527  1870   278   603  1434   171 

# summary(temp4$race.eth.7level)
# White Black Asian  AIAN  NHPI Other Mixed  NA's 
#  7527  1870   278    62    16   525  1434   171 

# We are going to use the five levels for race ("White", "Black", "Asian", "Other", "Mixed") and also use the variable demo_race_hispanic.

```




```{r}

# Save the new data frame again.
saveRDS(nda20, glue('{output_directory}/nda20.rds'))

# Save as csv file as well.
write.csv(nda20,glue('{output_directory}/nda20.csv'), row.names = FALSE)

```