---
title: "ABCD depression puberty reward - Exploratory - Demographics and behavioral data description and cleaning (confirmatory sample)"
date: "date started 01/july/20"
output:
  html_document: default
  pdf_document: default
authors: Lucia Magis Weinberg, Natalie Saragosa-Harris
---

```{LoadPackages, include=FALSE}
# Load packages.
#install.packages("devtools")
#devtools::install_github("easystats/report")
#devtools::install_github("goodekat/ggResidpanel")
#library(ggResidpanel)
#library(report)
packages <- c("tidyverse",   #data wrangling
             # "summarytools",  #data exploration and simple reporting
              "psych",          #correlations and Cronbach alpha for internal consistency  
              "readr",          #read csv
              "tidyr",          #create tidy data, where every column is a variable, every row is an observation 
              "dplyr",          #selecting columns, mutating, summarizing, etc.
              "Hmisc",          #correlations
              "RColorBrewer",   #choose nice colors for graphs
              "psychotools",    #psychometric modeling
              "knitr",          #Produce Rmarkdowns from Rnotebooks
              "lme4",           #run mixed effects regressions
              "lmerTest",       #compare different mixed effects models  
              "car",            #Companion to Applied Regression
              "haven",          #Import foreign statistical formats into R   
              "jtools",         #plot interactions 
              "apaTables",      #produce tables, might be redundant
              "DataExplorer",   #data exploration
              "interactions",   #interactions
              "ggstatsplot",    #pretty plots
              "ggplot2",        #other pretty plots
              "here",           #file navigation within a project
              "gtsummary")       #to make summary tables.  
#library("conflicted") #only run when there are issues with functions. Will illuminate which functions come from different packages
#invisible(lapply(packages, install.packages, character.only = TRUE)) #Only run once to install packages
library(tidyverse)
library(ggstatsplot)
library(here)
invisible(lapply(packages, library, character.only = TRUE))


# needed package to download from GitHub repo
#install.packages("remotes")
library(remotes)
# downloading the package from GitHub (needs `remotes` package to be installed)
remotes::install_github(
  repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub
  #dependencies = FALSE, # assumes you have already installed needed packages
  dependencies = TRUE, # installs packages which ggstatsplot depends on.
  #quick = TRUE # skips docs, demos, and vignettes
  upgrade_dependencies = TRUE # updates any out of date dependencies
)
```

```{GetData, include=FALSE}
# Load data.
## This script assumes that data has already been named and split into two halves.
## This script is based on the variable names on VariableDefinitions.csv

data_dir = ((dirname(here()))) #figure out how to navigate to data source

phase_folder = "confirmatory"  #select the appropiate folder

data_folder <- file.path(data_dir,"ABCD","derivatives",phase_folder)

file_name <- "nda20_confirmatory.csv" #specify file name here 

fulldata <- read.csv(file.path(data_folder,file_name))
#as_tibble(fulldata)
nrow(fulldata) # 5935.

```

```{r CreateDataframes, echo = FALSE}
# Call the script that keeps the columns of interest in the data and creates data frames that exclude outliers for certain variables.
script_path <- file.path(data_dir,"rewardprocesses_internalizing_puberty_exploratory","code","define_dataframes.R")
source(script_path)

```

```{r settheme, echo = FALSE}
nsh_theme <- theme(title= element_text(size=26, vjust=2, face="bold"),
         plot.title = element_blank(),
         axis.title.x= element_text(size=18, vjust=-0.3),
         axis.title.y= element_text(size=18, vjust=1.5),
         axis.text.x= element_text(size=18, colour="black"),
         axis.text.y= element_text(size=18, colour="black"),
         strip.text = element_text(size=24, face="bold"),
         panel.background = element_blank(),
         axis.line = element_line(colour = "black"))

```

```{r SummarizeMRIData, echo = FALSE}

# Create data tables for each subject of interest (PDS, brain measures, etc.).
# Note: For the MRI variables, I am ignoring the right and left hemisphere variables and only using the combined ones for now.

# All reward vs. neutral during anticipation stage (z scores).
MRI_anticipation_stage <- PDS_correct[,c("sex",
                    "accumbens_rvsn_ant_z",
                    "caudate_rvsn_ant_z",
                    "putamen_rvsn_ant_z",
                    "mOFC_rvsn_ant_z",
                    "lOFC_rvsn_ant_z",
                    "striatum_rvsn_ant_z")]

MRI_anticipation_stage %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      #digits = all_continuous() ~ 2,
                                      label = list(accumbens_rvsn_ant_z ~ "Accumbens (z)",
                                                   caudate_rvsn_ant_z ~ "Caudate (z)",
                                                   putamen_rvsn_ant_z ~ "Putamen (z)",
                                                   mOFC_rvsn_ant_z ~ "Medial OFC (z)",
                                                   lOFC_rvsn_ant_z ~ "Lateral OFC (z)",
                                                   striatum_rvsn_ant_z~ "Striatum Combined Areas (z)"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**Reward Anticipation Stage (Reward vs. Neutral)**")
 
# All positive vs. negative feedback.
MRI_feedback_stage <- PDS_correct[,c("sex",
                    "accumbens_posvsneg_feedback_z", 
                    "caudate_posvsneg_feedback_z",
                    "putamen_posvsneg_feedback_z",
                    "mOFC_posvsneg_feedback_z",
                    "lOFC_posvsneg_feedback_z",
                    "striatum_posvsneg_feedback_z")]

MRI_feedback_stage %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      #digits = all_continuous() ~ 2,
                                      label = list(accumbens_posvsneg_feedback_z ~ "Accumbens (z)",
                                                   caudate_posvsneg_feedback_z ~ "Caudate (z)",
                                                   putamen_posvsneg_feedback_z ~ "Putamen (z)",
                                                   mOFC_posvsneg_feedback_z ~ "Medial OFC (z)",
                                                   lOFC_posvsneg_feedback_z ~ "Lateral OFC (z)",
                                                   striatum_posvsneg_feedback_z ~ "Striatum Combined Areas (z)"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**Reward Feedback Stage (Positive vs. Negative)**")
 


```

```{r SummarizeBISBASData, echo = FALSE}
# Note: Currently in our variable definitions sheet, we only have this single variable for BIS/BAS, so that is the only one I am including here.
bisbas <- PDS_correct[,c("sex",
                    "bisbas_ss_basm_rr")]

bisbas %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      label = bisbas_ss_basm_rr ~ "BAS Reward Responsiveness",
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**BAS Reward Responsiveness**")

```

```{r SummarizeTestosteroneData, echo = FALSE}

testosterone <- PDS_correct[,c("sex",
                   "hormone_scr_ert_mean")]
                 
testosterone %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = hormone_scr_ert_mean ~ "Testosterone mean of measures (pg/mL)",
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**Testosterone**")

```

```{r SummarizeCBCLData, echo = FALSE}

# Plot raw scores.
CBCL_r <- PDS_correct[,c("sex",
                      "cbcl_scr_syn_internal_r",
                      "cbcl_scr_syn_anxdep_r",
                      "cbcl_scr_syn_withdep_r",
                      "cbcl_scr_dsm5_depress_r")]

CBCL_r %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = list(cbcl_scr_syn_internal_r ~ "Internalizing CBCL Syndrome Scale (raw score)",
                                                   cbcl_scr_syn_anxdep_r ~ "Anxious/Depressive CBCL Syndrome Scale (raw score)",
                                                   cbcl_scr_syn_withdep_r ~ "With Depression CBCL Syndrome Scale (raw score)",
                                                   cbcl_scr_dsm5_depress_r ~ "Depression CBCL DSM5 Scale (raw score)"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**CBCL**")

# Plot t scores (we will probably not be using these in our analyses, but worth looking at for now).
CBCL_t <- PDS_correct[,c("sex",
                      "cbcl_scr_syn_internal_t",
                      "cbcl_scr_syn_anxdep_t",
                      "cbcl_scr_syn_withdep_t",
                      "cbcl_scr_dsm5_depress_t")]

CBCL_t %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = list(cbcl_scr_syn_internal_t ~ "Internalizing CBCL Syndrome Scale (t-score)",
                                                   cbcl_scr_syn_anxdep_t ~ "Anxious/Depressive CBCL Syndrome Scale (t-score)",
                                                   cbcl_scr_syn_withdep_t ~ "With Depression CBCL Syndrome Scale (t-score)",
                                                   cbcl_scr_dsm5_depress_t ~ "Depression CBCL DSM5 Scale (t-score)"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**CBCL**")


```

```{r SummarizePDSData, echo = FALSE}

PDS <- PDS_correct[,c("sex",
                    "PDS_score",
                    "PDS_sum",
                    "pds_p_ss_category")]

PDS %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = list(PDS_score ~ "PDS score",
                                                   PDS_sum ~ "PDS sum",
                                                   pds_p_ss_category ~ "PDS category"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**PDS**")

```

```{r SummarizeDemographicData, echo = FALSE}

# Just to make the tables less long, I am going to put the demographics into two tables.
Demographics_1 <- PDS_correct[,c("interview_age",
                    "sex",
                    "race.ethnicity.5level",
                    "race.eth.7level",
                    "demo_race_hispanic")]

Demographics_2 <- PDS_correct[,c("interview_age",
                    "sex",
                    "high.educ",
                    "household.income",
                    "married.or.livingtogether")]

Demographics_1 %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = list(interview_age ~ "Age in months",
                                                   race.ethnicity.5level ~ "Race/Ethnicity (Five levels)",
                                                   race.eth.7level  ~ "Race/Ethnicity (Seven levels)",
                                                   demo_race_hispanic ~ "Hispanic"),
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**Demographics**")

Demographics_2 %>% tbl_summary(by = sex,
                                      statistic = list(all_continuous() ~ "{mean} ({sd}) [{min},{max}]",
                                      all_categorical() ~ "{n} / {N} ({p}%)"),
                                      digits = all_continuous() ~ 2,
                                      label = list(interview_age ~ "Age in months",
                                                   high.educ ~ "Parent highest education level",
                                                   household.income ~ "Household income",
                                                   married.or.livingtogether ~ "Married or living together"),
                                      type = married.or.livingtogether ~ "categorical",
                                      missing_text = "Missing Observations")  %>% modify_header(update = 
                          c(label ~ "**Variable**",
                            stat_1 ~ "*Female*",
                            stat_2 ~ "*Male*")) %>% modify_spanning_header(c("stat_1", "stat_2") ~ "**Demographics**")

```

```{TestosteroneDistributions}
PDS_correct$ERT_Hormone_Rounded <- floor(PDS_correct$hormone_scr_ert_mean) # I used the floor function to round down testosterone levels to a whole number. This creates a new variable (and so a new column), Testosterone_Rounded, in my dataframe (PDS_correct.
#PDS_correct$DHEA_Hormone_Rounded <- floor(PDS_correct$hormone_scr_dhea_mean) # DHEA
#PDS_correct$HSE_Hormone_Rounded <- floor(PDS_correct$hormone_scr_hse_mean) # Estrogen, only for women

# Example distribution: Plot testosterone levels (rounded down) in the sample.
max_level <- max(PDS_correct$ERT_Hormone_Rounded,na.rm = TRUE)
min_level <- min(PDS_correct$ERT_Hormone_Rounded,na.rm = TRUE)
total_plot <- ggplot(PDS_correct, aes(x=ERT_Hormone_Rounded)) + # this line is saying plot my data (PDS_correct), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=0.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=5))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Testosterone Levels by sex (Exploratory sample)",x = "Testosterone") + # Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{TestosteroneByGroup}
p <- ggplot(PDS_correct, aes(x=sex, y=ERT_Hormone_Rounded)) + 
  geom_boxplot()
p
```

```{BehavioralRewardDistributions}
# Example distribution: Plot BIS/BAS RR in the sample.
max_level <- max(PDS_correct$bisbas_ss_basm_rr,na.rm = TRUE)
min_level <- min(PDS_correct$bisbas_ss_basm_rr,na.rm = TRUE)
total_plot <- ggplot(PDS_correct, aes(x=bisbas_ss_basm_rr)) + # this line is saying plot my data (PDS_correct), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Reward responsiveness by sex (Exploratory sample)",x = "BIS/BAS RR")+ # Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{BehavioralRewardByGroup}
p <- ggplot(PDS_correct, aes(x=sex, y=bisbas_ss_basm_rr)) + 
  geom_boxplot()
p
```

```{BehavioralRewardByGender}
#RR by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = sex, # > 2 groups
  y = bisbas_ss_basm_rr,
  xlab = "Sex",
  ylab = "BIS/BAS RR score",
  title = "Reward responsiveness by sex",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```

```{CBCLDistributions}
# Example distribution: Plot CBCL (rounded down) in the sample.
max_level <- max(PDS_correct$cbcl_scr_syn_internal_r,na.rm = TRUE)
min_level <- min(PDS_correct$cbcl_scr_syn_internal_r,na.rm = TRUE)
total_plot <- ggplot(PDS_correct, aes(x=cbcl_scr_syn_internal_r)) +
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "CBCL Internalizing symptoms by sex (Exploratory sample)",x = "cbcl_scr_syn_internal_t") + # Set the title of the graph and label the x axis. 
facet_grid(. ~ sex)
total_plot
```

```{CBCLByGroup}
p <- ggplot(PDS_correct, aes(x=sex, y=cbcl_scr_syn_internal_t)) + 
  geom_boxplot()
p
```

```{CBCLWithDepressionDistributions}
# Example distribution: Plot CBCL (rounded down) in the sample.
max_level <- max(PDS_correct$cbcl_scr_syn_withdep_t,na.rm = TRUE)
min_level <- min(PDS_correct$cbcl_scr_syn_withdep_t,na.rm = TRUE)
total_plot <- ggplot(PDS_correct, aes(x=cbcl_scr_syn_withdep_t)) + # this line is saying plot my data (PDS_correct), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "CBCL withdrawn depression symptoms by sex (Exploratory sample)",x = "CBCL_scr_syn_withdep_t") +# Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{CBCLWithDepressionByGroup}
p <- ggplot(PDS_correct, aes(x=sex, y=cbcl_scr_syn_withdep_t)) + 
  geom_boxplot()
p
```

```{CBCLWithDepressionByGender}
#Withdrawn depression by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_internal_r,
  xlab = "Sex",
  ylab = "CBCL internalizing symptoms",
  title = "Withdrawn depressive symptoms by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```

```{r}
#Depression by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_internal_r,
  xlab = "Sex",
  ylab = "CBCL internalizing score",
  title = "Internalizing symptoms by sex",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
#file.name = (here("output","peru2_depression_gender.tiff"))
#ggsave(file.name,plot = last_plot(), dpi = 100, device = "tiff")
```

```{r}
#Depression by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_withdep_t,
  xlab = "Sex",
  ylab = "CBCL depression score",
  title = "Depressive symptoms by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```


```{PDSScoreDistributions}
# Plot PDS_score in the sample.
p <-  ggplot(PDS_correct, aes(PDS_score, ..count..)) + geom_bar(position = "dodge") + facet_grid(. ~ sex)
p

```

```{PDSScoreByGender}
#PDS score by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = sex, # > 2 groups
  y = PDS_score_both,
  xlab = "Sex",
  ylab = "PDS",
  title = "PDS by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
#file.name = (here("output","peru2_depression_gender.tiff"))
#ggsave(file.name,plot = last_plot(), dpi = 100, device = "tiff")
```

```{r}
#PDS score by gender
p <- ggbetweenstats(
  data = PDS_correct,
  x = race.eth.8level, # > 2 groups
  y = PDS_score_both,
  xlab = "Race/ethnicity",
  ylab = "PDS",
  grouping.var = sex,
  title = "PDS by race/ethnicity (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p 

```

```{PubertalCategory}
p <-  ggplot(PDS_correct, aes(pds_p_ss_category, ..count..)) + geom_bar(aes(fill = sex), position = "dodge")
p
```

#Brain
```{StriatumAnticipationDistributions}

max_level <- max(PDS_correct$striatum_rvsn_ant_z,na.rm = TRUE)
min_level <- min(PDS_correct$striatum_rvsn_ant_z,na.rm = TRUE)
total_plot <- ggplot(PDS_correct, aes(x=striatum_rvsn_ant_z)) +
              geom_histogram(binwidth=.5,alpha= 0.8) +
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) +
              labs(title = "Striatal activity during reward anticipation by sex (Exploratory sample)",x = "striatum_rvsn_ant_z") +
              facet_grid(. ~ sex)
total_plot
```

```{StriatumAnticipationByGroup}
p <- ggplot(PDS_correct, aes(x=sex, y=striatum_rvsn_ant_z)) + 
  geom_boxplot() + labs(title = "Striatal activity during reward anticipation by sex (Exploratory sample)",x = "striatum_rvsn_ant")

p
```