---
title: "ABCD depression puberty reward - Exploratory - Demographics and behavioral data description and cleaning"
date: "date started 01/july/20"
output:
  html_document: default
  pdf_document: default
authors: Lucia Magis Weinberg 
---

```{r, include=FALSE}
# Load packages
#install.packages("devtools")
#devtools::install_github("easystats/report")
#devtools::install_github("goodekat/ggResidpanel")
#library(ggResidpanel)
#library(report)
# Natalie adding comment.
packages <- c("tidyverse",   #data wrangling
             # "summarytools",  #data exploration and simple reporting
              "psych",       #correlations and Cronbach alpha for internal consistency  
              "readr",       #read csv
              "tidyr",       #create tidy data, where every column is a variable, every row is an                               observation 
              "Hmisc",          #correlations
              "RColorBrewer",   #choose nice colors for graphs
              "psychotools",    #psychometric modeling
              "knitr",          #Produce Rmarkdowns from Rnotebooks
              "lme4",           #run mixed effects regressions
              "lmerTest",       #compare different mixed effects models  
              "car",            #Companion to Applied Regression
              "haven",          #Import foreign statistical formats into R   
              "jtools",         #plot interactions 
              "apaTables",      #produce tables, might be redundant
              "DataExplorer",   #data exploration
              "interactions",   #interactions
              "ggstatsplot",    #pretty plots
              "ggplot2",        #other pretty plots
              "here")           #file navigation within a project
#library("conflicted") #only run when there are issues with functions. Will illuminate which functions come from different packages
#invisible(lapply(packages, install.packages, character.only = TRUE)) #Only run once to install packages
library(tidyverse)
library(ggstatsplot)
invisible(lapply(packages, library, character.only = TRUE))


# needed package to download from GitHub repo
install.packages("remotes")

# downloading the package from GitHub (needs `remotes` package to be installed)
remotes::install_github(
  repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub
  dependencies = FALSE, # assumes you have already installed needed packages
  quick = TRUE # skips docs, demos, and vignettes
)
```

```{r, include=FALSE}
# Load data
## This script assumes that data has already been names (with Natalie's code) and split into two halves
## This script is based on the variable names on VariableDefinitions.csv

data_dir = ((dirname(here()))) #figure out how to navigate to data source

phase_folder = "exploratory"  #select the appropiate folder
#phase_folder = "confirmatory"  #select the appropiate folder

data_folder <- file.path(data_dir,"ABCD","derivatives",phase_folder)  

file_name <- "nda20_exploratory.csv" #specify file name here 

fulldata <- read.csv(file.path(data_folder,file_name))
#as_tibble(fulldata)
```

```{r GetData, echo = FALSE}
#fulldata <- read.table(datafile, header=T, sep=",",as.is=TRUE,strip.white=TRUE,fill=TRUE)
nrow(fulldata) # 5934.
# Because this is such a big data file, let's only keep the columns that we need for this analysis.
data <- fulldata[,c("src_subject_id",
                "interview_age",
                "eventname",
                "sex",
                "site_id_l",
                "mri_info_deviceserialnumber",
                "rel_family_id",
                "race.ethnicity.5level",
                "race.eth.7level",
                "demo_race_hispanic", # Do you consider the child Hispanic/Latino/Latina?
                "high.educ",
                "household.income",
                "married.or.livingtogether",
                "bisbas_ss_basm_rr",
                "cbcl_scr_syn_internal_t",
                "cbcl_scr_syn_anxdep_t",
                "cbcl_scr_syn_withdep_t",
                "cbcl_scr_dsm5_depress_t",
                "cbcl_scr_syn_internal_r",
                "cbcl_scr_syn_anxdep_r",
                "cbcl_scr_syn_withdep_r",
                "cbcl_scr_dsm5_depress_r",
                "PDS_score_f",
                "PDS_score_m",
                "PDS_score",
                "PDS_sum_f",
                "PDS_sum_m",
                "PDS_sum",
                "pds_p_ss_category",
                "fam_history_q6d_depression",
                "tfmri_ma_acdn_b_scs_aarh", # Accumbens reward vs. neutral anticipation.
                "tfmri_ma_acdn_b_scs_aalh",
                "tfmri_ma_acdn_b_scs_cdrh", # Caudate reward vs. neutral anticipation.
                "tfmri_ma_acdn_b_scs_cdlh",
                "tfmri_ma_acdn_b_scs_ptrh", # Putamen reward vs. neutral anticipation.
                "tfmri_ma_acdn_b_scs_ptlh",
                "tfmri_ma_arvn_b_cds_mobofrrh", # Medial OFC reward vs. neutral anticipation.
                "tfmri_ma_arvn_b_cds_mobofrlh",
                "tfmri_ma_arvn_b_cds_lobofrrh", # Lateral OFC reward vs. neutral anticipation.
                "tfmri_ma_arvn_b_cds_lobofrlh",
                "tfmri_ma_rpvnfb_b_scs_aarh", # Accumbens reward positive versus negative feedback.
                "tfmri_ma_rpvnfb_b_scs_aalh",
                "tfmri_ma_rpvnfb_b_scs_cdrh", # Caudate reward positive versus negative feedback.
                "tfmri_ma_rpvnfb_b_scs_cdlh",
                "tfmri_ma_rpvnfb_b_scs_ptrh", # Putamen reward positive versus negative feedback.
                "tfmri_ma_rpvnfb_b_scs_ptlh",
                "tfmri_ma_rpvnfb_b_cds_mobofrrh", # Medial OFC reward positive versus negative feedback.
                "tfmri_ma_rpvnfb_b_cds_mobofrlh",
                "tfmri_ma_rpvnfb_b_cds_lobofrrh", # Lateral OFC reward positive versus negative feedback.
                "tfmri_ma_rpvnfb_b_cds_lobofrlh",
                "accumbens_rvsn_ant_z", # Reward vs. neutral during anticipation stage (z scores).
                "caudate_rvsn_ant_z",
                "putamen_rvsn_ant_z",
                "mOFC_rvsn_ant_z",
                "lOFC_rvsn_ant_z",
                "striatum_rvsn_ant_z", # reward vs. neutral anticipation.
                "accumbens_posvsneg_feedback_z", # All positive vs. negative feedback.
                "caudate_posvsneg_feedback_z",
                "putamen_posvsneg_feedback_z",
                "mOFC_posvsneg_feedback_z",
                "lOFC_posvsneg_feedback_z",
                "striatum_posvsneg_feedback_z"
                )]

data$src_subject_id <- as.factor(data$src_subject_id)
data$rel_family_id <- as.factor(data$rel_family_id)
data$eventname <- as.factor(data$eventname)
data$sex <- as.factor(data$sex)
data$demo_race_hispanic <- as.factor(data$demo_race_hispanic)
data$site_id_l <- as.factor(data$site_id_l)
data$mri_info_deviceserialnumber <- as.factor(data$mri_info_deviceserialnumber)
data$race.eth.7level <- as.factor(data$race.eth.7level)
data$high.educ <- as.factor(data$high.educ)
data$household.income <- as.factor(data$household.income)
data$married.or.livingtogether <- as.factor(data$married.or.livingtogether)
data$pds_p_ss_category <-as.factor(data$pds_p_ss_category)
data$race.ethnicity.5level = data$race.eth.7level
data$race.ethnicity.5level[(data$race.eth.7level == "AIAN" | data$race.eth.7level == "NHPI")] = "Other"
data$race.ethnicity.5level = droplevels(data$race.ethnicity.5level)

data$PDS_score_z<- scale(data$PDS_score)
data$cbcl_scr_syn_internal_r_z <- scale(data$cbcl_scr_syn_internal_r)

nrow(data) # 5934.

# Use data with only correct PDS scores.
PDS_correct <- subset(data, PDS_score < 5) #Be mindful that PDS category goes from 1 to 5, while PDS_average goes from 1 to 4 (continuous).
nrow(PDS_correct) # 4224.

PDS_correct <- subset(PDS_correct, PDS_sum<30) # This shouldn't change anything but just in case there is somehow a participant with a PDS score less than 5 but a sum that is incorrect.
nrow(PDS_correct) # 4224.
PDS_correct <- PDS_correct %>% filter(sex!="") #remove 6 participants with no gender.
nrow(PDS_correct) # 4224. Were these participants already removed from the dataframe?

# Separate by sex.
PDS_correct_females <- subset(PDS_correct, sex == "F")
PDS_correct_males <- subset(PDS_correct, sex == "M")
nrow(PDS_correct_females)  # 2059.
nrow(PDS_correct_males) # 2165.

# Create different subsets of the data based on removing outliers for specific variables of interest.
# No CBCL outliers.
data_no_CBCL_outliers <- subset(PDS_correct, cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_outliers) # 4152.

data_no_CBCL_outliers_females<- subset(PDS_correct_females, cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_outliers_females) # 2026.

data_no_CBCL_outliers_males<- subset(PDS_correct_males, cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_outliers_males) # 2126.

# No striatal anticipation outliers.
data_no_striatal_ant_outliers <- subset(PDS_correct, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3)
nrow(data_no_striatal_ant_outliers) # 4169.

data_no_striatal_ant_outliers_females <- subset(PDS_correct_females, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3)
nrow(data_no_striatal_ant_outliers_females) # 2035.

data_no_striatal_ant_outliers_males <- subset(PDS_correct_males, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3)
nrow(data_no_striatal_ant_outliers_males) # 2134.

# No CBCL or striatal anticipation outliers.
data_no_CBCL_striatal_ant_outliers <- subset(PDS_correct, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3 & cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_striatal_ant_outliers) # 4097.

data_no_CBCL_striatal_ant_outliers_females <- subset(PDS_correct_females, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3 & cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_striatal_ant_outliers_females) # 2002.

data_no_CBCL_striatal_ant_outliers_males <- subset(PDS_correct_males, striatum_rvsn_ant_z > -3 & striatum_rvsn_ant_z < 3 & cbcl_scr_syn_internal_r_z > -3 & cbcl_scr_syn_internal_r_z < 3)
nrow(data_no_CBCL_striatal_ant_outliers_males) # 2095.

```

```{r settheme, echo = FALSE}
nsh_theme <- theme(title= element_text(size=26, vjust=2, face="bold"),
         plot.title = element_blank(),
         axis.title.x= element_text(size=18, vjust=-0.3),
         axis.title.y= element_text(size=18, vjust=1.5),
         axis.text.x= element_text(size=18, colour="black"),
         axis.text.y= element_text(size=18, colour="black"),
         strip.text = element_text(size=24, face="bold"),
         panel.background = element_blank(),
         axis.line = element_line(colour = "black"))

```


```{r}
# 
ABCD_Data$src_subject_id<- as.factor(ABCD_Data$src_subject_id) # check that this is the correct column for participant IDs.
ABCD_Data$ERT_Hormone_Rounded <- floor(ABCD_Data$hormone_scr_ert_mean) # I used the floor function to round down testosterone levels to a whole number. This creates a new variable (and so a new column), Testosterone_Rounded, in my dataframe (ABCD_Data).
#ABCD_Data$DHEA_Hormone_Rounded <- floor(ABCD_Data$hormone_scr_dhea_mean) # DHEA
#ABCD_Data$HSE_Hormone_Rounded <- floor(ABCD_Data$hormone_scr_hse_mean) # Estrogen, only for women
```

```{r}
# Example distribution: Plot testosterone levels (rounded down) in the sample.
max_level <- max(ABCD_Data$ERT_Hormone_Rounded,na.rm = TRUE)
min_level <- min(ABCD_Data$ERT_Hormone_Rounded,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=ERT_Hormone_Rounded)) + # this line is saying plot my data (ABCD_Data), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=0.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=5))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Testosterone Levels by sex (Exploratory sample)",x = "Testosterone") + # Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{r}
p <- ggplot(ABCD_Data, aes(x=sex, y=ERT_Hormone_Rounded)) + 
  geom_boxplot()
p
```

```{r}
# Example distribution: Plot BIS/BAS RR in the sample.
max_level <- max(ABCD_Data$bisbas_ss_basm_rr,na.rm = TRUE)
min_level <- min(ABCD_Data$bisbas_ss_basm_rr,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=bisbas_ss_basm_rr)) + # this line is saying plot my data (ABCD_Data), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Reward responsiveness by sex (Exploratory sample)",x = "BIS/BAS RR")+ # Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```
```{r}
p <- ggplot(ABCD_Data, aes(x=sex, y=bisbas_ss_basm_rr)) + 
  geom_boxplot()
p
```
```{r}
#RR by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = sex, # > 2 groups
  y = bisbas_ss_basm_rr,
  xlab = "Sex",
  ylab = "BIS/BAS RR score",
  title = "Reward responsiveness by sex",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```



```{r}
# Example distribution: Plot CBCL (rounded down) in the sample.
max_level <- max(ABCD_Data$cbcl_scr_syn_internal_r,na.rm = TRUE)
min_level <- min(ABCD_Data$cbcl_scr_syn_internal_r,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=cbcl_scr_syn_internal_r)) +
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "CBCL Internalizing symptoms by sex (Exploratory sample)",x = "cbcl_scr_syn_internal_t") + # Set the title of the graph and label the x axis. 
facet_grid(. ~ sex)
total_plot
```
```{r}
p <- ggplot(ABCD_Data, aes(x=sex, y=cbcl_scr_syn_internal_t)) + 
  geom_boxplot()
p
```


```{r}
# Example distribution: Plot CBCL (rounded down) in the sample.
max_level <- max(ABCD_Data$cbcl_scr_syn_withdep_t,na.rm = TRUE)
min_level <- min(ABCD_Data$cbcl_scr_syn_withdep_t,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=cbcl_scr_syn_withdep_t)) + # this line is saying plot my data (ABCD_Data), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "CBCL withdrawn depression symptoms by sex (Exploratory sample)",x = "CBCL_scr_syn_withdep_t") +# Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```
```{r}
p <- ggplot(ABCD_Data, aes(x=sex, y=cbcl_scr_syn_withdep_t)) + 
  geom_boxplot()
p
```

```{r}
#Withdrawn depression by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_internal_r,
  xlab = "Sex",
  ylab = "CBCL internalizing symptoms",
  title = "Withdrawn depressive symptoms by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```

```{r}
#Depression by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_internal_r,
  xlab = "Sex",
  ylab = "CBCL internalizing score",
  title = "Internalizing symptoms by sex",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
#file.name = (here("output","peru2_depression_gender.tiff"))
#ggsave(file.name,plot = last_plot(), dpi = 100, device = "tiff")
```

```{r}
#Depression by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = sex, # > 2 groups
  y = cbcl_scr_syn_withdep_t,
  xlab = "Sex",
  ylab = "CBCL depression score",
  title = "Depressive symptoms by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
```


```{r}
# Example distribution: Plot PDS_score in the sample.
max_level <- max(ABCD_Data$PDS_score_both,na.rm = TRUE)
min_level <- min(ABCD_Data$PDS_score_both,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=PDS_score_both)) + # this line is saying plot my data (ABCD_Data), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=1))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Self-reported pubertal development by sex (Exploratory sample)",x = "PDS score") +# Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{r}
#PDS score by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = sex, # > 2 groups
  y = PDS_score_both,
  xlab = "Sex",
  ylab = "PDS",
  title = "PDS by sex (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p
#file.name = (here("output","peru2_depression_gender.tiff"))
#ggsave(file.name,plot = last_plot(), dpi = 100, device = "tiff")
```

```{r}
#PDS score by gender
p <- ggbetweenstats(
  data = ABCD_Data,
  x = race.eth.8level, # > 2 groups
  y = PDS_score_both,
  xlab = "Race/ethnicity",
  ylab = "PDS",
  grouping.var = sex,
  title = "PDS by race/ethnicity (Exploratory sample)",
  bf.message  = FALSE,
  pairwise.display = "significant", # display only significant pairwise comparisons
  pairwise.annotation = "p.value", # annotate the pairwise comparisons using p-values
  p.adjust.method = "fdr", # adjust p-values for multiple tests using this method
  messages = FALSE,
  palette = "Set2",
  package = "RColorBrewer",
  ggstatsplot.layer = FALSE,
  ggplot.component = list(theme(axis.text.y= element_text(size = 14,face="bold"),
                                axis.text.x = element_text(size = 14,face="bold"),
                                axis.title.x = element_text(size = 16,face="bold"),
                                axis.title.y = element_text(size = 16,face="bold"),
                                plot.subtitle = element_text(size = 12),
                                title =element_text(size=18, face='bold')))
)

p 

```

#Brain
```{r}
# Example distribution: Plot CBCL (rounded down) in the sample.
max_level <- max(ABCD_Data$striatum_rvsn_ant,na.rm = TRUE)
min_level <- min(ABCD_Data$striatum_rvsn_ant,na.rm = TRUE)
total_plot <- ggplot(ABCD_Data, aes(x=striatum_rvsn_ant)) + # this line is saying plot my data (ABCD_Data), with the x axis being their rounded testosterone.
              geom_histogram(binwidth=.5,alpha= 0.8) + # this is specifying the width of the histogram bars and how transparent the color is (that is the alpha).
              scale_x_continuous(breaks=c(seq(min_level, max_level, by=10))) + # include mininum to maximum observed values on the axis and to plot by intervals of 5.
              labs(title = "Striatal activity during reward anticipation by sex (Exploratory sample)",x = "striatum_rvsn_ant") +# Set the title of the graph and label the x axis.
facet_grid(. ~ sex)
total_plot
```

```{r}
p <- ggplot(ABCD_Data, aes(x=sex, y=striatum_rvsn_ant)) + 
  geom_boxplot() + labs(title = "Striatal activity during reward anticipation by sex (Exploratory sample)",x = "striatum_rvsn_ant")# Set the title of the graph and label the x axis.
p
```

```{r, Pubertal category}
p <-  ggplot(data, aes(pds_p_ss_category, ..count..)) + geom_bar(aes(fill = sex), position = "dodge")
```

