---
title: "ABCD depression puberty reward - Code to split sample in exploratory and confirmatory samples"
output: html_notebook
date: "date started 01/july/20"
output:
  html_document: default
  pdf_document: default
authors: Lucia Magis Weinberg 
---

```{r, include=FALSE}
# Load packages
#install.packages("devtools")
#devtools::install_github("easystats/report")
#devtools::install_github("goodekat/ggResidpanel")
#library(ggResidpanel)
#library(report)


#NEW COMMENT

packages <- c("tidyverse",   #data wrangling
              "summarytools",  #data exploration and simple reporting
              "psych",       #correlations and Cronbach alpha for internal consistency  
              "readr",       #read csv
              "tidyr",       #create tidy data, where every column is a variable, every row is an                               observation 
              "Hmisc",          #correlations
              "RColorBrewer",   #choose nice colors for graphs
              "psychotools",    #psychometric modeling
              "knitr",          #Produce Rmarkdowns from Rnotebooks
              "lme4",           #run mixed effects regressions
              "lmerTest",       #compare different mixed effects models  
              "car",            #Companion to Applied Regression
              "haven",          #Import foreign statistical formats into R   
              "jtools",         #plot interactions 
              "apaTables",      #produce tables, might be redundant
              "DataExplorer",   #data exploration
              "interactions",   #interactions
              "ggstatsplot",    #pretty plots
              "here")           #file navigation within a project
#library("conflicted") #only run when there are issues with functions. Will illuminate which functions come from different packages
#invisible(lapply(packages, install.packages, character.only = TRUE)) #Only run once to install packages
library(tidyverse)
invisible(lapply(packages, library, character.only = TRUE))
```


```{r, include=FALSE}
# Load data
## This script assumes that data has already been names (with Natalie's code) and split into two halves
## This script is based on the variable names on VariableDefinitions.csv

data_dir = (dirname(dirname(here()))) #figure out how to navigate to data source

phase_folder = "all_baseline"  #select the appropiate folder
phase_folder = "exploratory"  #select the appropiate folder
phase_folder = "confirmatory"  #select the appropiate folder

data_folder <- file.path(data_dir,"Phases",phase_folder,"data")  

file_name <- "ABCD_allpartipants_baseline.csv" #specify file name here 

ABCD_Data <- read.csv(file.path(data_folder,file_name))
as_tibble(ABCD_Data)
```

```{r}

setwd("C:/Users/lucia/Dropbox/Projects_Postdoc/ABCD puberty reward processing mental health/data/raw")
ABCD_Data <- read.table("C:/Users/lucia/Dropbox/Projects_Postdoc/ABCD puberty reward processing mental health/data/raw/ABCD_puberty_reward_mentalhealth_release21_withfix.csv", header=T, sep=",",as.is=TRUE,strip.white=TRUE,fill=TRUE)
```

```{r}
#Select only baseline
library(janitor)
ABCD_Data_baseline <- ABCD_Data %>% filter(eventname=="baseline_year_1_arm_1")
nrow(ABCD_Data_baseline)

ABCD_Data_baseline <- ABCD_Data_baseline %>% filter(gender!="") #remove 6 participants with no gender
nrow(ABCD_Data_baseline)
```

```{r}
#Baseline comparison between genders
library(compareGroups)

reduced.ABCD.table<- ABCD_Data_baseline %>% 
  select(interview_age,gender,cbcl_scr_syn_internal_t,hormone_scr_ert_mean)

table <- compareGroups(gender ~ ., data = reduced.ABCD.table,na.omit(TRUE))
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)
export_table

export2word(export_table, file = (here("output","fullsample_means_gender.doc")))  
```

```{r}
#By block
library(randomizr)
set.seed(343)

ABCD_Data_baseline$Z <- block_ra(blocks = c(ABCD_Data_baseline$gender))
table(ABCD_Data_baseline$Z, ABCD_Data_baseline$gender)

reduced.ABCD.table<- ABCD_Data_baseline %>% 
  select(interview_age,gender,cbcl_scr_syn_internal_t,hormone_scr_ert_mean,Z)

table <- compareGroups(Z ~ ., data = reduced.ABCD.table,na.omit(TRUE))
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)
export_table
```





```{r}
ABCD_Data_exploratory <- ABCD_Data_baseline[(ABCD_Data_baseline$Z==0),]
ABCD_Data_confirmatory <- ABCD_Data_baseline[(ABCD_Data_baseline$Z==1),]
```

```{r}
reduced.ABCDexp.table<- ABCD_Data_exploratory %>% 
  select(interview_age,gender,cbcl_scr_syn_internal_t,hormone_scr_ert_mean)

table <- compareGroups(gender ~ ., data =reduced.ABCDexp.table,na.omit(TRUE))
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)
export_table

#export2word(export_table, file = (here("output","fullsample_means_gender.doc")))  
```



```{r}
reduced.ABCDexp.table<- ABCD_Data_exploratory %>% 
  select(interview_age,gender,cbcl_scr_syn_internal_t,hormone_scr_ert_mean)

table <- compareGroups(gender ~ ., data =reduced.ABCDexp.table,na.omit(TRUE))
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)
export_table

#export2word(export_table, file = (here("output","fullsample_means_gender.doc")))  
```

```{r}
reduced.ABCDconf.table<- ABCD_Data_confirmatory %>% 
  select(interview_age,gender,cbcl_scr_syn_internal_t,hormone_scr_ert_mean)

table <- compareGroups(gender ~ ., data =reduced.ABCDconf.table,na.omit(TRUE))
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)
export_table

#export2word(export_table, file = (here("output","fullsample_means_gender.doc")))  
```

```{r}
#By cluster
clusters <- with(ABCD_Data, paste(gender,mri_info_manufacturer,sep = "_"))
ABCD_Data$clusters <- clusters

Z_clust <- cluster_ra(clusters = clusters)

table(Z_clust,clusters)
```